alias: Add State Class to Gas and Water Consumption Sensors
trigger:
  - platform: state
    entity_id:
      - sensor.gas_consumption
      - sensor.water_consumption
  - platform: homeassistant
    event: start
action:
  - delay: "00:00:30"
  - service: python_script.add_state_class
    data: {}
